# Generated by Django 4.2.5 on 2023-10-07 06:23

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('phone', models.CharField(max_length=150)),
                ('slug', models.SlugField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_activated', models.DateTimeField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('agent_type', models.CharField(blank=True, choices=[('a', 'Agent'), ('b', 'Broker')], default='a', help_text='Agent type', max_length=1, verbose_name='type')),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agents',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('days_on_market', models.IntegerField()),
                ('image', models.FileField(blank=True, upload_to='listing_images/')),
                ('slug', models.SlugField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_activated', models.DateTimeField(blank=True, null=True)),
                ('date_available', models.DateTimeField(blank=True, default=listings.models.one_day_after, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('listing_type', models.CharField(blank=True, choices=[('s', 'Sale'), ('r', 'Rent'), ('s', 'Staging'), ('n', 'Renovation')], default='r', help_text='Listing type', max_length=1, verbose_name='type')),
                ('listing_status', models.CharField(blank=True, choices=[('r', 'Created'), ('a', 'Active'), ('c', 'Cancelled'), ('e', 'Ended')], default='r', help_text='Listing type', max_length=1, verbose_name='status')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('conditions', models.TextField()),
                ('date_closing', models.DateTimeField()),
                ('client_id', models.IntegerField()),
                ('realtor_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_closed', models.DateTimeField(null=True)),
                ('offer_status', models.CharField(blank=True, choices=[('ir', 'In Review'), ('re', 'Rejected'), ('ac', 'Accepted'), ('cl', 'Closed')], default='ir', help_text='Offer status', max_length=2, verbose_name='status')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'real estate',
                'verbose_name_plural': 'real estates',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('address_line1', models.CharField(max_length=150)),
                ('address_line2', models.CharField(blank=True, max_length=150)),
                ('address_line3', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('building_size', models.IntegerField()),
                ('floor_size', models.IntegerField()),
                ('lot_size', models.IntegerField()),
                ('block_size', models.IntegerField(blank=True, null=True)),
                ('bedroom_number', models.IntegerField()),
                ('bathroom_number', models.IntegerField()),
                ('parking_number', models.IntegerField()),
                ('market_value', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(null=True)),
                ('is_commercial', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_built', models.DateField(blank=True, null=True)),
                ('date_activated', models.DateTimeField(blank=True, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('property_type', models.CharField(blank=True, choices=[('ho', 'House'), ('th', 'Townhouse'), ('bu', 'Bungalow'), ('sf', 'Singlefamily'), ('mf', 'Multifamily'), ('ma', 'Mansion'), ('ap', 'Apartment'), ('co', 'Condo'), ('fl', 'Flat'), ('ca', 'Cabin'), ('fm', 'Farmhouse'), ('ra', 'Ranch'), ('la', 'Land'), ('of', 'Office'), ('re', 'Retail'), ('ht', 'Hotel'), ('we', 'Warehouse'), ('ot', 'Other')], default='ho', help_text='Property type', max_length=2, verbose_name='type')),
                ('features', models.ManyToManyField(help_text='Select a feature for the property', to='listings.feature')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='ListingAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_side', models.CharField(blank=True, choices=[('s', 'Seller'), ('b', 'Buyer')], default='s', help_text='Agent side', max_length=1, verbose_name='side')),
                ('agent_role', models.CharField(blank=True, choices=[('ag', 'Agent'), ('ap', 'Appraisal'), ('pm', 'Property Manager')], default='ag', help_text='Agent role', max_length=2, verbose_name='role')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.agent')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='agents',
            field=models.ManyToManyField(help_text='Select an agent for the listing', through='listings.ListingAgent', to='listings.agent'),
        ),
        migrations.AddField(
            model_name='listing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.property'),
        ),
        migrations.AddField(
            model_name='agent',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='listings.realestate'),
        ),
    ]
