# Generated by Django 4.2.5 on 2023-09-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, upload_to='listing_images/'),
        ),
    ]
