# Generated by Django 4.2.5 on 2023-09-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='agent_side',
        ),
        migrations.AddField(
            model_name='listingagent',
            name='agent_role',
            field=models.CharField(blank=True, choices=[('ag', 'Agent'), ('ap', 'Appraisal'), ('pm', 'Property Manager')], default='ag', help_text='Agent role', max_length=2, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='listingagent',
            name='agent_side',
            field=models.CharField(blank=True, choices=[('s', 'Seller'), ('b', 'Buyer')], default='s', help_text='Agent side', max_length=1, verbose_name='side'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('s', 'Sale'), ('r', 'Rent'), ('s', 'Staging'), ('n', 'Renovation')], default='r', help_text='Listing type', max_length=1, verbose_name='type'),
        ),
    ]
