# Generated by Django 4.2.6 on 2023-11-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_category_post_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
    ]
