# Generated by Django 4.2.6 on 2023-11-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_category_options_alter_story_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='story',
            table='story',
        ),
    ]
